[program:worker-argusz-nightwatch]
command=php /var/www/html/artisan nightwatch:agent
process_name=%(program_name)s_%(process_num)02d
user=www-data
numprocs=1
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker-files.log
stdout_logfile_maxbytes=0